# Generated by Django 3.2.3 on 2021-06-07 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='vote_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время голосования'),
            preserve_default=False,
        ),
    ]
