# Generated by Django 3.2.3 on 2021-07-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0002_uservote_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия'),
        ),
    ]
