# Generated by Django 3.2.3 on 2021-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0004_telegramuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='send_contact_text',
            field=models.CharField(default='Вы должны отправить свой контакт перед голосованием!', max_length=255, verbose_name='Текст всплывающего окна запроса номера телефона'),
        ),
    ]
