# Generated by Django 3.2.3 on 2021-06-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0004_auto_20210601_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Номинация', 'verbose_name_plural': 'номинации'},
        ),
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='model',
            name='nominations',
            field=models.ManyToManyField(through='kasdeutsch_bot.Vote', to='kasdeutsch_bot.Nomination', verbose_name='Номинации'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.nomination', verbose_name='Номинация'),
        ),
    ]
