# Generated by Django 3.2.3 on 2021-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0005_botcontent_send_contact_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='share_contact',
            field=models.CharField(default='Поделиться контактом', max_length=40, verbose_name='Текст кнопки "Поделиться контактом"'),
        ),
    ]
