# Generated by Django 3.2.3 on 2021-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0006_botcontent_share_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='description',
            field=models.TextField(default='Кандидаты номинации'),
        ),
    ]
