# Generated by Django 3.2.3 on 2021-06-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0006_auto_20210602_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.model')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.nomination')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='votes',
            field=models.ManyToManyField(through='kasdeutsch_bot.UserVote', to='kasdeutsch_bot.Nomination'),
        ),
    ]
