# Generated by Django 3.2.3 on 2021-06-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0007_auto_20210603_0124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('tg_user', 'nomination')},
        ),
    ]
