# Generated by Django 3.2.3 on 2021-06-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0008_alter_uservote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='voted',
        ),
    ]
