# Generated by Django 3.2.3 on 2021-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0008_auto_20210804_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramstate',
            name='request_phone_number_message_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
