# Generated by Django 3.2.3 on 2021-06-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0009_remove_telegramuser_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(blank=True, default=1, verbose_name='Рейтинг'),
        ),
    ]
