# Generated by Django 4.2.2 on 2023-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0011_alter_competition_image_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='every_nomination_vote_required',
            field=models.BooleanField(default=False, verbose_name='Необходимо голосовать в каждой номинации'),
        ),
    ]
