# Generated by Django 3.2.3 on 2021-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0011_alter_vote_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='image',
            field=models.ImageField(default='demo_nomination.png', upload_to='', verbose_name='Фото'),
        ),
    ]
