# Generated by Django 4.2.2 on 2023-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0013_remove_botcontent_every_nomination_vote_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='was_checked_and_credited',
            field=models.CharField(default='Ваши голоса во всех номинациях были учтены!', max_length=50, verbose_name='Текст после нажатия кнопки "Проголосовать", когда голос был учтён у текущей модели и во всех номинациях (если такая настройка включена)'),
        ),
    ]
