# Generated by Django 4.2.2 on 2023-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0014_botcontent_was_checked_and_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='was_checked_not_credited',
            field=models.CharField(default='Ваши голоса будут учтены когда проголосуете во всех номинациях!', max_length=50, verbose_name='Текст после нажатия кнопки "Проголосовать", когда голос не был учтён, но сохранён (если такая настройка включена)'),
        ),
    ]
