# Generated by Django 3.2.3 on 2021-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0014_auto_20210604_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='competition',
            name='about',
            field=models.TextField(default='', verbose_name='О конкурсе'),
        ),
    ]
