# Generated by Django 4.2.2 on 2023-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0015_botcontent_was_checked_not_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontent',
            name='was_checked_not_credited',
            field=models.CharField(default='Голоса будут учтены после голоса во всех номинациях!', max_length=55, verbose_name='Текст после нажатия кнопки "Проголосовать", когда голос не был учтён, но сохранён (если такая настройка включена)'),
        ),
    ]
