# Generated by Django 3.2.3 on 2021-06-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0015_auto_20210604_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='О конкурсе'),
        ),
    ]
