# Generated by Django 4.2.2 on 2023-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0016_alter_botcontent_was_checked_not_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='should_request_name_and_job',
            field=models.BooleanField(default=False, verbose_name='Запрашивать у пользователей имя и должность для данного конкурса'),
        ),
    ]
