# Generated by Django 3.2.3 on 2021-06-04 15:41

from django.db import migrations, models
import kasdeutsch_bot.models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0017_auto_20210604_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50, verbose_name='Текст кнопки "О конкурсе"')),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='image',
            field=models.ImageField(default='demo_nomination1234.png', upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Фото'),
        ),
    ]
