# Generated by Django 4.2.2 on 2023-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0017_competition_should_request_name_and_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='job',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
    ]
