# Generated by Django 3.2.3 on 2021-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0018_auto_20210604_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontent',
            name='about',
            field=models.CharField(blank=True, default='О конкурсе', max_length=50, verbose_name='Текст кнопки "О конкурсе"'),
        ),
    ]
