# Generated by Django 3.2.3 on 2021-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0019_alter_botcontent_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcontent',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'настройки'},
        ),
        migrations.AddField(
            model_name='botcontent',
            name='chose_nomination',
            field=models.CharField(default='Выберите номинацию, в которой хотите проголосовать. У вас есть один голос в каждой номинации.', max_length=255, verbose_name='Текст меню выбора номинации'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='about',
            field=models.CharField(default='О конкурсе', max_length=50, verbose_name='Текст кнопки "О конкурсе"'),
        ),
    ]
