# Generated by Django 3.2.3 on 2021-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0020_auto_20210604_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='no_competition',
            field=models.CharField(default='Нет активных конкурсов.', max_length=255, verbose_name='Текст меню когда конкурс отсутствует'),
        ),
    ]
