# Generated by Django 3.2.3 on 2021-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0021_botcontent_no_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='already_voted',
            field=models.CharField(default='Ваш голос уже был учтён!', max_length=255, verbose_name='Текст всплывающего окна, когда голос учтён'),
        ),
    ]
