# Generated by Django 3.2.3 on 2021-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0022_botcontent_already_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='update',
            field=models.CharField(default='Обновить', max_length=50, verbose_name='Текст кнопки "Обновить"'),
        ),
    ]
