# Generated by Django 3.2.3 on 2021-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0023_botcontent_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='back',
            field=models.CharField(default='Назад', max_length=50, verbose_name='Текст кнопки "Назад"'),
        ),
    ]
