# Generated by Django 3.2.3 on 2021-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0024_botcontent_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='no_competition_image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Фото для сообщения "Нет соревнования"'),
        ),
    ]
