# Generated by Django 3.2.3 on 2021-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0025_botcontent_no_competition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='votes',
            field=models.CharField(default='голосов', max_length=255, verbose_name='Текст списка моделей (когда человек проголосовал)'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='votess',
            field=models.CharField(default='голосов, включая ваш', max_length=255, verbose_name='Текст списка моделей (когда человек проголосовал, включая его голос)'),
        ),
    ]
