# Generated by Django 3.2.3 on 2021-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0026_auto_20210604_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='candidates',
            field=models.CharField(default='Кандидаты номинации', max_length=255, verbose_name='Текст меню списка кандидатов'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='votes',
            field=models.CharField(default='голосов', max_length=255, verbose_name='Текст кандидата когда человек проголосовал'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='votess',
            field=models.CharField(default='голосов, включая ваш', max_length=255, verbose_name='Текст кандидата когда человек проголосовал, включая его голос'),
        ),
    ]
