# Generated by Django 3.2.3 on 2021-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0027_auto_20210604_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='update_menu',
            field=models.CharField(default='Пожалуйста, обновите информацию о конкурсе!', max_length=255, verbose_name='Текст меню обновления конкурса'),
        ),
    ]
