# Generated by Django 3.2.3 on 2021-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0028_botcontent_update_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='vote',
            field=models.CharField(default='Проголосовать!', max_length=50, verbose_name='Текст кнопки "Проголосовать"'),
        ),
    ]
