# Generated by Django 3.2.3 on 2021-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0029_botcontent_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='was_checked',
            field=models.CharField(default='Ваш голос за эту модель был учтён', max_length=50, verbose_name='Текст кнопки "Проголосовать", когда голос был учтён'),
        ),
    ]
