# Generated by Django 3.2.3 on 2021-06-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0030_botcontent_was_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='update_menu_image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Фото для меню обновления конкурса'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='was_checked_in_this_nomination',
            field=models.CharField(default='Вы уже проголосовали за модель в этой номинации!', max_length=50, verbose_name='Текст кнопки "Проголосовать", когда голос был учтён у другой модели в этой категории'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='was_checked',
            field=models.CharField(default='Ваш голос за эту модель был учтён!', max_length=50, verbose_name='Текст кнопки "Проголосовать", когда голос был учтён у текущей модели'),
        ),
    ]
