# Generated by Django 3.2.3 on 2021-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0031_auto_20210604_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='default_model_photo',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Дефолтное фото кандидата'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='next_photo',
            field=models.CharField(default='>', max_length=50, verbose_name='Текст кнопки следующей фотографии'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='prev_photo',
            field=models.CharField(default='<', max_length=50, verbose_name='Текст кнопки предыдущей фотографии'),
        ),
    ]
