# Generated by Django 3.2.3 on 2021-06-04 16:32

from django.db import migrations, models
import kasdeutsch_bot.models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0032_auto_20210604_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontent',
            name='default_model_photo',
            field=models.ImageField(upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Дефолтное фото кандидата'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='no_competition_image',
            field=models.ImageField(upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Фото для сообщения "Нет соревнования"'),
        ),
        migrations.AlterField(
            model_name='botcontent',
            name='update_menu_image',
            field=models.ImageField(upload_to='', validators=[kasdeutsch_bot.models.validate_image], verbose_name='Фото для меню обновления конкурса'),
        ),
    ]
