# Generated by Django 3.2.3 on 2021-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0033_auto_20210604_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcontent',
            name='hide_bio',
            field=models.CharField(default='Скрыть биографию', max_length=50, verbose_name='Текст кнопки "Скрыть биографию"'),
        ),
        migrations.AddField(
            model_name='botcontent',
            name='show_bio',
            field=models.CharField(default='Биография', max_length=50, verbose_name='Текст кнопки "Показать биографию"'),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография'),
        ),
    ]
