# Generated by Django 3.2.3 on 2021-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0002_auto_20210601_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='nominations',
            field=models.ManyToManyField(to='kasdeutsch_bot.Nomination', verbose_name='Номинации'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
