# Generated by Django 3.2.3 on 2021-06-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0003_auto_20210601_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.model')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasdeutsch_bot.nomination')),
            ],
        ),
        migrations.AlterField(
            model_name='model',
            name='nominations',
            field=models.ManyToManyField(through='kasdeutsch_bot.Vote', to='kasdeutsch_bot.Nomination'),
        ),
    ]
