# Generated by Django 3.2.3 on 2021-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0005_auto_20210601_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-rating'], 'verbose_name': 'Голосование', 'verbose_name_plural': 'голосования'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='voted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Проголосовал'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
