# Generated by Django 3.2.3 on 2021-06-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasdeutsch_bot', '0010_alter_vote_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
    ]
